# Generated by Django 5.1.7 on 2025-04-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrito',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Pago',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='pedido',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='stlmodelo',
            old_name='usuario',
            new_name='user',
        ),
    ]
