# Generated by Django 5.1.7 on 2025-05-06 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_carrito_cart_rename_pedido_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STLModelo',
            new_name='STLModel',
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.user')),
            ],
        ),
    ]
