# Generated by Django 5.1.7 on 2025-05-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_stlmodelo_stlmodel_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
    ]
