# Generated by Django 5.2.6 on 2025-09-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_product_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mostrar_inicio',
            field=models.BooleanField(default=True),
        ),
    ]
