# Generated by Django 5.2.6 on 2025-10-28 23:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, help_text='Identificador amigable opcional usado por la interfaz.', max_length=120, null=True, unique=True)),
                ('sku', models.CharField(max_length=120, unique=True)),
                ('material', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('diameter', models.DecimalField(decimal_places=2, default=Decimal('1.75'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))])),
                ('grams_available', models.PositiveIntegerField(default=0)),
                ('grams_reserved', models.PositiveIntegerField(default=0)),
                ('reorder_point_grams', models.PositiveIntegerField(default=0)),
                ('grams_per_unit', models.PositiveIntegerField(default=0, help_text='Consumo estimado por pieza en gramos.')),
                ('est_print_min_per_unit', models.PositiveIntegerField(default=0, help_text='Tiempo estimado por pieza en minutos.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['material', 'color', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(help_text='Identificador legible usado por el panel.', max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('online', 'online'), ('maintenance', 'maintenance'), ('offline', 'offline')], default='online', max_length=20)),
                ('nozzle', models.CharField(blank=True, max_length=20)),
                ('avg_speed_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))])),
                ('maintenance_every_hours', models.PositiveIntegerField(default=120)),
                ('maintenance_hours_used', models.PositiveIntegerField(default=0)),
                ('last_maintenance_at', models.DateTimeField(blank=True, null=True)),
                ('compatible_materials', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='MachineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('est_minutes_per_unit', models.PositiveIntegerField(default=0)),
                ('remaining_minutes', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ventas.machine')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FilamentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=64)),
                ('grams', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ventas.filament')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order_id', 'filament'), name='unique_reservation_per_filament_and_order')],
            },
        ),
    ]
