# Generated by Django 4.2.20 on 2025-04-29 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='product_name',
        ),
        migrations.AddField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('output', 'Output'), ('input', 'Input')], max_length=20),
        ),
    ]