# Generated by Django 5.2.6 on 2025-09-24 18:31

import ventas_user_admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_user_admin', '0002_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ventas_user_admin.models.UserManager()),
            ],
        ),
    ]
